/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DefaultDetailsModel model module.
 * @module model/DefaultDetailsModel
 * @version v1.0
 */
class DefaultDetailsModel {
    /**
     * Constructs a new <code>DefaultDetailsModel</code>.
     * A model representing an instance of loan default, the failure to repay debt associated with a given loan
     * @alias module:model/DefaultDetailsModel
     */
    constructor() { 
        
        DefaultDetailsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DefaultDetailsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DefaultDetailsModel} obj Optional instance to populate.
     * @return {module:model/DefaultDetailsModel} The populated <code>DefaultDetailsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DefaultDetailsModel();

            if (data.hasOwnProperty('reason')) {
                obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
            }
            if (data.hasOwnProperty('reasonDetails')) {
                obj['reasonDetails'] = ApiClient.convertToType(data['reasonDetails'], 'String');
            }
            if (data.hasOwnProperty('dateDefaulted')) {
                obj['dateDefaulted'] = ApiClient.convertToType(data['dateDefaulted'], 'Date');
            }
            if (data.hasOwnProperty('currentAmountAtTimeOfDefault')) {
                obj['currentAmountAtTimeOfDefault'] = ApiClient.convertToType(data['currentAmountAtTimeOfDefault'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the reason, put concisely, for the default
 * @member {String} reason
 */
DefaultDetailsModel.prototype['reason'] = undefined;

/**
 * Gets or sets a more detailed account of the reason for default
 * @member {String} reasonDetails
 */
DefaultDetailsModel.prototype['reasonDetails'] = undefined;

/**
 * Gets or sets the date on which default occurred
 * @member {Date} dateDefaulted
 */
DefaultDetailsModel.prototype['dateDefaulted'] = undefined;

/**
 * Gets or sets the loan's Current Amount at the time of default
 * @member {Number} currentAmountAtTimeOfDefault
 */
DefaultDetailsModel.prototype['currentAmountAtTimeOfDefault'] = undefined;






export default DefaultDetailsModel;

