/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EarlyRenewalDetailsModel model module.
 * @module model/EarlyRenewalDetailsModel
 * @version v1.0
 */
class EarlyRenewalDetailsModel {
    /**
     * Constructs a new <code>EarlyRenewalDetailsModel</code>.
     * A model detailing an instance of Early Renewal
     * @alias module:model/EarlyRenewalDetailsModel
     */
    constructor() { 
        
        EarlyRenewalDetailsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EarlyRenewalDetailsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EarlyRenewalDetailsModel} obj Optional instance to populate.
     * @return {module:model/EarlyRenewalDetailsModel} The populated <code>EarlyRenewalDetailsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EarlyRenewalDetailsModel();

            if (data.hasOwnProperty('oldLoanId')) {
                obj['oldLoanId'] = ApiClient.convertToType(data['oldLoanId'], 'String');
            }
            if (data.hasOwnProperty('oldLoanNumber')) {
                obj['oldLoanNumber'] = ApiClient.convertToType(data['oldLoanNumber'], 'Number');
            }
            if (data.hasOwnProperty('isOldLoanRepaid')) {
                obj['isOldLoanRepaid'] = ApiClient.convertToType(data['isOldLoanRepaid'], 'Boolean');
            }
            if (data.hasOwnProperty('newLoanId')) {
                obj['newLoanId'] = ApiClient.convertToType(data['newLoanId'], 'String');
            }
            if (data.hasOwnProperty('newLoanNumber')) {
                obj['newLoanNumber'] = ApiClient.convertToType(data['newLoanNumber'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Loan ID of the loan which was renewed
 * @member {String} oldLoanId
 */
EarlyRenewalDetailsModel.prototype['oldLoanId'] = undefined;

/**
 * Gets or sets the Loan Number of the loan which was renewed
 * @member {Number} oldLoanNumber
 */
EarlyRenewalDetailsModel.prototype['oldLoanNumber'] = undefined;

/**
 * Gets or sets a value indicating whether the loan which was renewed has been fully repaid
 * @member {Boolean} isOldLoanRepaid
 */
EarlyRenewalDetailsModel.prototype['isOldLoanRepaid'] = undefined;

/**
 * Gets or sets the Loan ID of the Early Remewal loan created
 * @member {String} newLoanId
 */
EarlyRenewalDetailsModel.prototype['newLoanId'] = undefined;

/**
 * Gets or sets the Loan Number of the Early Remewal loan created
 * @member {Number} newLoanNumber
 */
EarlyRenewalDetailsModel.prototype['newLoanNumber'] = undefined;






export default EarlyRenewalDetailsModel;

