/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoanFundingPaymentModel model module.
 * @module model/LoanFundingPaymentModel
 * @version v1.0
 */
class LoanFundingPaymentModel {
    /**
     * Constructs a new <code>LoanFundingPaymentModel</code>.
     * A model characterising a given funding payment
     * @alias module:model/LoanFundingPaymentModel
     */
    constructor() { 
        
        LoanFundingPaymentModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoanFundingPaymentModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoanFundingPaymentModel} obj Optional instance to populate.
     * @return {module:model/LoanFundingPaymentModel} The populated <code>LoanFundingPaymentModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanFundingPaymentModel();

            if (data.hasOwnProperty('paymentDate')) {
                obj['paymentDate'] = ApiClient.convertToType(data['paymentDate'], 'Date');
            }
            if (data.hasOwnProperty('paymentAmount')) {
                obj['paymentAmount'] = ApiClient.convertToType(data['paymentAmount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Payment Date
 * @member {Date} paymentDate
 */
LoanFundingPaymentModel.prototype['paymentDate'] = undefined;

/**
 * Gets or sets the Payment Amount
 * @member {Number} paymentAmount
 */
LoanFundingPaymentModel.prototype['paymentAmount'] = undefined;






export default LoanFundingPaymentModel;

