/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoanWriteOffDetailsModel model module.
 * @module model/LoanWriteOffDetailsModel
 * @version v1.0
 */
class LoanWriteOffDetailsModel {
    /**
     * Constructs a new <code>LoanWriteOffDetailsModel</code>.
     * A model detailing the write-off of a given loan, if applicable
     * @alias module:model/LoanWriteOffDetailsModel
     */
    constructor() { 
        
        LoanWriteOffDetailsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoanWriteOffDetailsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoanWriteOffDetailsModel} obj Optional instance to populate.
     * @return {module:model/LoanWriteOffDetailsModel} The populated <code>LoanWriteOffDetailsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanWriteOffDetailsModel();

            if (data.hasOwnProperty('paymentDate')) {
                obj['paymentDate'] = ApiClient.convertToType(data['paymentDate'], 'Date');
            }
            if (data.hasOwnProperty('paymentAmount')) {
                obj['paymentAmount'] = ApiClient.convertToType(data['paymentAmount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Payment Date
 * @member {Date} paymentDate
 */
LoanWriteOffDetailsModel.prototype['paymentDate'] = undefined;

/**
 * Gets or sets the Payment Amount
 * @member {Number} paymentAmount
 */
LoanWriteOffDetailsModel.prototype['paymentAmount'] = undefined;






export default LoanWriteOffDetailsModel;

