/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RefinancingLoanDetailsModel from './RefinancingLoanDetailsModel';

/**
 * The LoanRefinancingDetailsModel model module.
 * @module model/LoanRefinancingDetailsModel
 * @version v1.0
 */
class LoanRefinancingDetailsModel {
    /**
     * Constructs a new <code>LoanRefinancingDetailsModel</code>.
     * A model detailing the refinancing of a given loan, if applicable
     * @alias module:model/LoanRefinancingDetailsModel
     */
    constructor() { 
        
        LoanRefinancingDetailsModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoanRefinancingDetailsModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoanRefinancingDetailsModel} obj Optional instance to populate.
     * @return {module:model/LoanRefinancingDetailsModel} The populated <code>LoanRefinancingDetailsModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanRefinancingDetailsModel();

            if (data.hasOwnProperty('refinancingFromLoanDetails')) {
                obj['refinancingFromLoanDetails'] = RefinancingLoanDetailsModel.constructFromObject(data['refinancingFromLoanDetails']);
            }
            if (data.hasOwnProperty('refinancingToLoanDetails')) {
                obj['refinancingToLoanDetails'] = RefinancingLoanDetailsModel.constructFromObject(data['refinancingToLoanDetails']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RefinancingLoanDetailsModel} refinancingFromLoanDetails
 */
LoanRefinancingDetailsModel.prototype['refinancingFromLoanDetails'] = undefined;

/**
 * @member {module:model/RefinancingLoanDetailsModel} refinancingToLoanDetails
 */
LoanRefinancingDetailsModel.prototype['refinancingToLoanDetails'] = undefined;






export default LoanRefinancingDetailsModel;

