/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoanRepaymentModel model module.
 * @module model/LoanRepaymentModel
 * @version v1.0
 */
class LoanRepaymentModel {
    /**
     * Constructs a new <code>LoanRepaymentModel</code>.
     * A model detailing the repayments made on a particular loan
     * @alias module:model/LoanRepaymentModel
     */
    constructor() { 
        
        LoanRepaymentModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoanRepaymentModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoanRepaymentModel} obj Optional instance to populate.
     * @return {module:model/LoanRepaymentModel} The populated <code>LoanRepaymentModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanRepaymentModel();

            if (data.hasOwnProperty('transactionHistoryId')) {
                obj['transactionHistoryId'] = ApiClient.convertToType(data['transactionHistoryId'], 'String');
            }
            if (data.hasOwnProperty('paymentDate')) {
                obj['paymentDate'] = ApiClient.convertToType(data['paymentDate'], 'Date');
            }
            if (data.hasOwnProperty('totalCardTransactions')) {
                obj['totalCardTransactions'] = ApiClient.convertToType(data['totalCardTransactions'], 'Number');
            }
            if (data.hasOwnProperty('sweep')) {
                obj['sweep'] = ApiClient.convertToType(data['sweep'], 'Number');
            }
            if (data.hasOwnProperty('repaymentAmount')) {
                obj['repaymentAmount'] = ApiClient.convertToType(data['repaymentAmount'], 'Number');
            }
            if (data.hasOwnProperty('loanBalance')) {
                obj['loanBalance'] = ApiClient.convertToType(data['loanBalance'], 'Number');
            }
            if (data.hasOwnProperty('payments')) {
                obj['payments'] = ApiClient.convertToType(data['payments'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the Transaction History ID
 * @member {String} transactionHistoryId
 */
LoanRepaymentModel.prototype['transactionHistoryId'] = undefined;

/**
 * Gets or sets the Payment Date
 * @member {Date} paymentDate
 */
LoanRepaymentModel.prototype['paymentDate'] = undefined;

/**
 * Gets or sets the Total Card Transactions value
 * @member {Number} totalCardTransactions
 */
LoanRepaymentModel.prototype['totalCardTransactions'] = undefined;

/**
 * Gets or sets the Sweep, a decimal out of 100 representing the proportion of transaction income which this repayment represents
 * @member {Number} sweep
 */
LoanRepaymentModel.prototype['sweep'] = undefined;

/**
 * Gets or sets the Repayment Amount
 * @member {Number} repaymentAmount
 */
LoanRepaymentModel.prototype['repaymentAmount'] = undefined;

/**
 * Gets or sets the Loan Balance
 * @member {Number} loanBalance
 */
LoanRepaymentModel.prototype['loanBalance'] = undefined;

/**
 * Gets or sets the record of Payments
 * @member {Array.<Number>} payments
 */
LoanRepaymentModel.prototype['payments'] = undefined;






export default LoanRepaymentModel;

