/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefaultDetailsModel from './DefaultDetailsModel';
import EarlyRenewalDetailsModel from './EarlyRenewalDetailsModel';
import LoanDocumentModel from './LoanDocumentModel';
import LoanFundingDetailsModel from './LoanFundingDetailsModel';
import LoanOwnerModel from './LoanOwnerModel';
import LoanRefinancingDetailsModel from './LoanRefinancingDetailsModel';
import LoanWriteOffDetailsModel from './LoanWriteOffDetailsModel';
import ThirdPartyReferenceModel from './ThirdPartyReferenceModel';

/**
 * The LoanModel model module.
 * @module model/LoanModel
 * @version v1.0
 */
class LoanModel {
    /**
     * Constructs a new <code>LoanModel</code>.
     * A model representing the details of an individual loan
     * @alias module:model/LoanModel
     */
    constructor() { 
        
        LoanModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoanModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoanModel} obj Optional instance to populate.
     * @return {module:model/LoanModel} The populated <code>LoanModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoanModel();

            if (data.hasOwnProperty('autoRepaymentSweep')) {
                obj['autoRepaymentSweep'] = ApiClient.convertToType(data['autoRepaymentSweep'], 'Boolean');
            }
            if (data.hasOwnProperty('borrowerId')) {
                obj['borrowerId'] = ApiClient.convertToType(data['borrowerId'], 'String');
            }
            if (data.hasOwnProperty('borrowerName')) {
                obj['borrowerName'] = ApiClient.convertToType(data['borrowerName'], 'String');
            }
            if (data.hasOwnProperty('creditRating')) {
                obj['creditRating'] = ApiClient.convertToType(data['creditRating'], 'String');
            }
            if (data.hasOwnProperty('currencyISOCode')) {
                obj['currencyISOCode'] = ApiClient.convertToType(data['currencyISOCode'], 'String');
            }
            if (data.hasOwnProperty('currentAmount')) {
                obj['currentAmount'] = ApiClient.convertToType(data['currentAmount'], 'Number');
            }
            if (data.hasOwnProperty('currentServiceChargeRate')) {
                obj['currentServiceChargeRate'] = ApiClient.convertToType(data['currentServiceChargeRate'], 'Number');
            }
            if (data.hasOwnProperty('defaultDetails')) {
                obj['defaultDetails'] = DefaultDetailsModel.constructFromObject(data['defaultDetails']);
            }
            if (data.hasOwnProperty('discount')) {
                obj['discount'] = ApiClient.convertToType(data['discount'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('lenderId')) {
                obj['lenderId'] = ApiClient.convertToType(data['lenderId'], 'String');
            }
            if (data.hasOwnProperty('lenderName')) {
                obj['lenderName'] = ApiClient.convertToType(data['lenderName'], 'String');
            }
            if (data.hasOwnProperty('maturityDate')) {
                obj['maturityDate'] = ApiClient.convertToType(data['maturityDate'], 'Date');
            }
            if (data.hasOwnProperty('originalAmount')) {
                obj['originalAmount'] = ApiClient.convertToType(data['originalAmount'], 'Number');
            }
            if (data.hasOwnProperty('originalProjectedAnnualisedReturn')) {
                obj['originalProjectedAnnualisedReturn'] = ApiClient.convertToType(data['originalProjectedAnnualisedReturn'], 'Number');
            }
            if (data.hasOwnProperty('originalServiceChargeRate')) {
                obj['originalServiceChargeRate'] = ApiClient.convertToType(data['originalServiceChargeRate'], 'Number');
            }
            if (data.hasOwnProperty('projectedRepaymentDate')) {
                obj['projectedRepaymentDate'] = ApiClient.convertToType(data['projectedRepaymentDate'], 'Date');
            }
            if (data.hasOwnProperty('securityAndGuarantees')) {
                obj['securityAndGuarantees'] = ApiClient.convertToType(data['securityAndGuarantees'], 'Boolean');
            }
            if (data.hasOwnProperty('loanType')) {
                obj['loanType'] = ApiClient.convertToType(data['loanType'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('sweep')) {
                obj['sweep'] = ApiClient.convertToType(data['sweep'], 'Number');
            }
            if (data.hasOwnProperty('useOfProceeds')) {
                obj['useOfProceeds'] = ApiClient.convertToType(data['useOfProceeds'], 'String');
            }
            if (data.hasOwnProperty('loanNumber')) {
                obj['loanNumber'] = ApiClient.convertToType(data['loanNumber'], 'Number');
            }
            if (data.hasOwnProperty('refinancingDetails')) {
                obj['refinancingDetails'] = LoanRefinancingDetailsModel.constructFromObject(data['refinancingDetails']);
            }
            if (data.hasOwnProperty('earlyRenewalDetails')) {
                obj['earlyRenewalDetails'] = EarlyRenewalDetailsModel.constructFromObject(data['earlyRenewalDetails']);
            }
            if (data.hasOwnProperty('fundingDetails')) {
                obj['fundingDetails'] = LoanFundingDetailsModel.constructFromObject(data['fundingDetails']);
            }
            if (data.hasOwnProperty('writeOffDetails')) {
                obj['writeOffDetails'] = LoanWriteOffDetailsModel.constructFromObject(data['writeOffDetails']);
            }
            if (data.hasOwnProperty('owners')) {
                obj['owners'] = ApiClient.convertToType(data['owners'], [LoanOwnerModel]);
            }
            if (data.hasOwnProperty('thirdPartyReferences')) {
                obj['thirdPartyReferences'] = ApiClient.convertToType(data['thirdPartyReferences'], [ThirdPartyReferenceModel]);
            }
            if (data.hasOwnProperty('documents')) {
                obj['documents'] = ApiClient.convertToType(data['documents'], [LoanDocumentModel]);
            }
        }
        return obj;
    }


}

/**
 * Gets or sets a value indicating whether an Auto Repayment Sweep is to be used - this feature automatically directs a chosen proportion, the Sweep, of transaction income towards repaying the loan
 * @member {Boolean} autoRepaymentSweep
 */
LoanModel.prototype['autoRepaymentSweep'] = undefined;

/**
 * Gets or sets the Borrower ID
 * @member {String} borrowerId
 */
LoanModel.prototype['borrowerId'] = undefined;

/**
 * Gets or sets the Borrower Name
 * @member {String} borrowerName
 */
LoanModel.prototype['borrowerName'] = undefined;

/**
 * Gets or sets the Credit Rating
 * @member {String} creditRating
 */
LoanModel.prototype['creditRating'] = undefined;

/**
 * Gets or sets the Currency ISO Code
 * @member {String} currencyISOCode
 */
LoanModel.prototype['currencyISOCode'] = undefined;

/**
 * Gets or sets the Current Amount, the amount yet to be repaid
 * @member {Number} currentAmount
 */
LoanModel.prototype['currentAmount'] = undefined;

/**
 * Gets or sets the Current Service Charge Rate
 * @member {Number} currentServiceChargeRate
 */
LoanModel.prototype['currentServiceChargeRate'] = undefined;

/**
 * @member {module:model/DefaultDetailsModel} defaultDetails
 */
LoanModel.prototype['defaultDetails'] = undefined;

/**
 * Gets or sets the loan's discount rate
 * @member {Number} discount
 */
LoanModel.prototype['discount'] = undefined;

/**
 * Gets or sets the loan's unique identifier
 * @member {String} id
 */
LoanModel.prototype['id'] = undefined;

/**
 * Gets or sets the lender's unique identifier
 * @member {String} lenderId
 */
LoanModel.prototype['lenderId'] = undefined;

/**
 * Gets or sets the lender's full name
 * @member {String} lenderName
 */
LoanModel.prototype['lenderName'] = undefined;

/**
 * Gets or sets the date on which the loan is due to mature, and by which it should be fully repaid
 * @member {Date} maturityDate
 */
LoanModel.prototype['maturityDate'] = undefined;

/**
 * Gets or sets the Original Amount, the total amount due to be repaid on maturity
 * @member {Number} originalAmount
 */
LoanModel.prototype['originalAmount'] = undefined;

/**
 * Gets or sets the Original Projected Annualised Return
 * @member {Number} originalProjectedAnnualisedReturn
 */
LoanModel.prototype['originalProjectedAnnualisedReturn'] = undefined;

/**
 * Gets or sets the Original Service Charge Rate
 * @member {Number} originalServiceChargeRate
 */
LoanModel.prototype['originalServiceChargeRate'] = undefined;

/**
 * Gets or sets the Projected Repayment Date
 * @member {Date} projectedRepaymentDate
 */
LoanModel.prototype['projectedRepaymentDate'] = undefined;

/**
 * Gets or sets a value indicating whether the Security and Guarantees are in place
 * @member {Boolean} securityAndGuarantees
 */
LoanModel.prototype['securityAndGuarantees'] = undefined;

/**
 * Gets or sets the Loan Type - \"Initial\", \"Refinanced\" or \"Renewal\"
 * @member {String} loanType
 */
LoanModel.prototype['loanType'] = undefined;

/**
 * Gets or sets the loan's Status - \"Deleted\", \"Funded\", \"Funded (Pending Settlement)\", \"Refinanced\", \"Repaid\", \"Written Off\"
 * @member {String} status
 */
LoanModel.prototype['status'] = undefined;

/**
 * Gets or sets the Sweep, the decimal out of 100 representing the proportion of transaction income to be used to repay the loan
 * @member {Number} sweep
 */
LoanModel.prototype['sweep'] = undefined;

/**
 * Gets or sets the Use Of Proceeds, i.e. to what end the loaned funds will be used
 * @member {String} useOfProceeds
 */
LoanModel.prototype['useOfProceeds'] = undefined;

/**
 * Gets or sets the Loan Number, an ordinal value indicating which of a customer's loans is here detailed
 * @member {Number} loanNumber
 */
LoanModel.prototype['loanNumber'] = undefined;

/**
 * @member {module:model/LoanRefinancingDetailsModel} refinancingDetails
 */
LoanModel.prototype['refinancingDetails'] = undefined;

/**
 * @member {module:model/EarlyRenewalDetailsModel} earlyRenewalDetails
 */
LoanModel.prototype['earlyRenewalDetails'] = undefined;

/**
 * @member {module:model/LoanFundingDetailsModel} fundingDetails
 */
LoanModel.prototype['fundingDetails'] = undefined;

/**
 * @member {module:model/LoanWriteOffDetailsModel} writeOffDetails
 */
LoanModel.prototype['writeOffDetails'] = undefined;

/**
 * Gets or sets a collection detailing the loan's Owners YL.Web.Api.ThirdParty.Loan.Models.LoanOwnerModel
 * @member {Array.<module:model/LoanOwnerModel>} owners
 */
LoanModel.prototype['owners'] = undefined;

/**
 * Gets or sets the loan's Third Party References YL.Web.Api.ThirdParty.Loan.Models.ThirdPartyReferenceModel
 * @member {Array.<module:model/ThirdPartyReferenceModel>} thirdPartyReferences
 */
LoanModel.prototype['thirdPartyReferences'] = undefined;

/**
 * Gets or sets the Documents YL.Web.Api.ThirdParty.Loan.Models.LoanDocumentModel supporting the loan application
 * @member {Array.<module:model/LoanDocumentModel>} documents
 */
LoanModel.prototype['documents'] = undefined;






export default LoanModel;

