/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ThirdPartyReferenceModel model module.
 * @module model/ThirdPartyReferenceModel
 * @version v1.0
 */
class ThirdPartyReferenceModel {
    /**
     * Constructs a new <code>ThirdPartyReferenceModel</code>.
     * A model detailing any references provided by a third party for a given loan
     * @alias module:model/ThirdPartyReferenceModel
     */
    constructor() { 
        
        ThirdPartyReferenceModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ThirdPartyReferenceModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ThirdPartyReferenceModel} obj Optional instance to populate.
     * @return {module:model/ThirdPartyReferenceModel} The populated <code>ThirdPartyReferenceModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ThirdPartyReferenceModel();

            if (data.hasOwnProperty('thirdPartyId')) {
                obj['thirdPartyId'] = ApiClient.convertToType(data['thirdPartyId'], 'String');
            }
            if (data.hasOwnProperty('thirdPartyReference')) {
                obj['thirdPartyReference'] = ApiClient.convertToType(data['thirdPartyReference'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Gets or sets the third party's unique identifier
 * @member {String} thirdPartyId
 */
ThirdPartyReferenceModel.prototype['thirdPartyId'] = undefined;

/**
 * Gets or sets the reference provided by the third party
 * @member {String} thirdPartyReference
 */
ThirdPartyReferenceModel.prototype['thirdPartyReference'] = undefined;






export default ThirdPartyReferenceModel;

