/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyLoanApiClient);
  }
}(this, function(expect, YlThirdPartyLoanApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoanRepaymentModel', function() {
    it('should create an instance of LoanRepaymentModel', function() {
      // uncomment below and update the code to test LoanRepaymentModel
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be.a(YlThirdPartyLoanApiClient.LoanRepaymentModel);
    });

    it('should have the property transactionHistoryId (base name: "transactionHistoryId")', function() {
      // uncomment below and update the code to test the property transactionHistoryId
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

    it('should have the property paymentDate (base name: "paymentDate")', function() {
      // uncomment below and update the code to test the property paymentDate
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

    it('should have the property totalCardTransactions (base name: "totalCardTransactions")', function() {
      // uncomment below and update the code to test the property totalCardTransactions
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

    it('should have the property sweep (base name: "sweep")', function() {
      // uncomment below and update the code to test the property sweep
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

    it('should have the property repaymentAmount (base name: "repaymentAmount")', function() {
      // uncomment below and update the code to test the property repaymentAmount
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

    it('should have the property loanBalance (base name: "loanBalance")', function() {
      // uncomment below and update the code to test the property loanBalance
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

    it('should have the property payments (base name: "payments")', function() {
      // uncomment below and update the code to test the property payments
      //var instane = new YlThirdPartyLoanApiClient.LoanRepaymentModel();
      //expect(instance).to.be();
    });

  });

}));
