/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyLoanApiClient);
  }
}(this, function(expect, YlThirdPartyLoanApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyLoanApiClient.LoansModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoansModel', function() {
    it('should create an instance of LoansModel', function() {
      // uncomment below and update the code to test LoansModel
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be.a(YlThirdPartyLoanApiClient.LoansModel);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property loanNumber (base name: "loanNumber")', function() {
      // uncomment below and update the code to test the property loanNumber
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property lenderId (base name: "lenderId")', function() {
      // uncomment below and update the code to test the property lenderId
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property lenderName (base name: "lenderName")', function() {
      // uncomment below and update the code to test the property lenderName
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property borrowerId (base name: "borrowerId")', function() {
      // uncomment below and update the code to test the property borrowerId
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property borrowerName (base name: "borrowerName")', function() {
      // uncomment below and update the code to test the property borrowerName
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property currentAmount (base name: "currentAmount")', function() {
      // uncomment below and update the code to test the property currentAmount
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property loanType (base name: "loanType")', function() {
      // uncomment below and update the code to test the property loanType
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property maturityDate (base name: "maturityDate")', function() {
      // uncomment below and update the code to test the property maturityDate
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property sweep (base name: "sweep")', function() {
      // uncomment below and update the code to test the property sweep
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property autoRepaymentSweep (base name: "autoRepaymentSweep")', function() {
      // uncomment below and update the code to test the property autoRepaymentSweep
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property currencyISOCode (base name: "currencyISOCode")', function() {
      // uncomment below and update the code to test the property currencyISOCode
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property lendingPartnerIds (base name: "lendingPartnerIds")', function() {
      // uncomment below and update the code to test the property lendingPartnerIds
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property owners (base name: "owners")', function() {
      // uncomment below and update the code to test the property owners
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property currentAmountAtRepay (base name: "currentAmountAtRepay")', function() {
      // uncomment below and update the code to test the property currentAmountAtRepay
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property currentAmountAtDelete (base name: "currentAmountAtDelete")', function() {
      // uncomment below and update the code to test the property currentAmountAtDelete
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

    it('should have the property currentAmountAtWriteOff (base name: "currentAmountAtWriteOff")', function() {
      // uncomment below and update the code to test the property currentAmountAtWriteOff
      //var instane = new YlThirdPartyLoanApiClient.LoansModel();
      //expect(instance).to.be();
    });

  });

}));
