/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyLoanApiClient);
  }
}(this, function(expect, YlThirdPartyLoanApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyLoanApiClient.LoanOwnerModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoanOwnerModel', function() {
    it('should create an instance of LoanOwnerModel', function() {
      // uncomment below and update the code to test LoanOwnerModel
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be.a(YlThirdPartyLoanApiClient.LoanOwnerModel);
    });

    it('should have the property ownerLenderId (base name: "ownerLenderId")', function() {
      // uncomment below and update the code to test the property ownerLenderId
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property ownerLenderNumber (base name: "ownerLenderNumber")', function() {
      // uncomment below and update the code to test the property ownerLenderNumber
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property ownershipPercentage (base name: "ownershipPercentage")', function() {
      // uncomment below and update the code to test the property ownershipPercentage
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property ownershipPaymentStatus (base name: "ownershipPaymentStatus")', function() {
      // uncomment below and update the code to test the property ownershipPaymentStatus
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property ownershipPaymentAmountPaid (base name: "ownershipPaymentAmountPaid")', function() {
      // uncomment below and update the code to test the property ownershipPaymentAmountPaid
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property expectedOwnershipPaymentAmount (base name: "expectedOwnershipPaymentAmount")', function() {
      // uncomment below and update the code to test the property expectedOwnershipPaymentAmount
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property ownerName (base name: "ownerName")', function() {
      // uncomment below and update the code to test the property ownerName
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property refinancingRepaymentAmountDue (base name: "refinancingRepaymentAmountDue")', function() {
      // uncomment below and update the code to test the property refinancingRepaymentAmountDue
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property totalRepaymentsReceived (base name: "totalRepaymentsReceived")', function() {
      // uncomment below and update the code to test the property totalRepaymentsReceived
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property totalRepaymentsOwed (base name: "totalRepaymentsOwed")', function() {
      // uncomment below and update the code to test the property totalRepaymentsOwed
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property generatedTransferAgreement (base name: "generatedTransferAgreement")', function() {
      // uncomment below and update the code to test the property generatedTransferAgreement
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

    it('should have the property transferAgreementDocumentSigningId (base name: "transferAgreementDocumentSigningId")', function() {
      // uncomment below and update the code to test the property transferAgreementDocumentSigningId
      //var instane = new YlThirdPartyLoanApiClient.LoanOwnerModel();
      //expect(instance).to.be();
    });

  });

}));
