/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyLoanApiClient);
  }
}(this, function(expect, YlThirdPartyLoanApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyLoanApiClient.LoanModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LoanModel', function() {
    it('should create an instance of LoanModel', function() {
      // uncomment below and update the code to test LoanModel
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be.a(YlThirdPartyLoanApiClient.LoanModel);
    });

    it('should have the property autoRepaymentSweep (base name: "autoRepaymentSweep")', function() {
      // uncomment below and update the code to test the property autoRepaymentSweep
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property borrowerId (base name: "borrowerId")', function() {
      // uncomment below and update the code to test the property borrowerId
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property borrowerName (base name: "borrowerName")', function() {
      // uncomment below and update the code to test the property borrowerName
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property creditRating (base name: "creditRating")', function() {
      // uncomment below and update the code to test the property creditRating
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property currencyISOCode (base name: "currencyISOCode")', function() {
      // uncomment below and update the code to test the property currencyISOCode
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property currentAmount (base name: "currentAmount")', function() {
      // uncomment below and update the code to test the property currentAmount
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property currentServiceChargeRate (base name: "currentServiceChargeRate")', function() {
      // uncomment below and update the code to test the property currentServiceChargeRate
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property defaultDetails (base name: "defaultDetails")', function() {
      // uncomment below and update the code to test the property defaultDetails
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property lenderId (base name: "lenderId")', function() {
      // uncomment below and update the code to test the property lenderId
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property lenderName (base name: "lenderName")', function() {
      // uncomment below and update the code to test the property lenderName
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property maturityDate (base name: "maturityDate")', function() {
      // uncomment below and update the code to test the property maturityDate
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property originalAmount (base name: "originalAmount")', function() {
      // uncomment below and update the code to test the property originalAmount
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property originalProjectedAnnualisedReturn (base name: "originalProjectedAnnualisedReturn")', function() {
      // uncomment below and update the code to test the property originalProjectedAnnualisedReturn
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property originalServiceChargeRate (base name: "originalServiceChargeRate")', function() {
      // uncomment below and update the code to test the property originalServiceChargeRate
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property projectedRepaymentDate (base name: "projectedRepaymentDate")', function() {
      // uncomment below and update the code to test the property projectedRepaymentDate
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property securityAndGuarantees (base name: "securityAndGuarantees")', function() {
      // uncomment below and update the code to test the property securityAndGuarantees
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property loanType (base name: "loanType")', function() {
      // uncomment below and update the code to test the property loanType
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property sweep (base name: "sweep")', function() {
      // uncomment below and update the code to test the property sweep
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property useOfProceeds (base name: "useOfProceeds")', function() {
      // uncomment below and update the code to test the property useOfProceeds
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property loanNumber (base name: "loanNumber")', function() {
      // uncomment below and update the code to test the property loanNumber
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property refinancingDetails (base name: "refinancingDetails")', function() {
      // uncomment below and update the code to test the property refinancingDetails
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property earlyRenewalDetails (base name: "earlyRenewalDetails")', function() {
      // uncomment below and update the code to test the property earlyRenewalDetails
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property fundingDetails (base name: "fundingDetails")', function() {
      // uncomment below and update the code to test the property fundingDetails
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property writeOffDetails (base name: "writeOffDetails")', function() {
      // uncomment below and update the code to test the property writeOffDetails
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property owners (base name: "owners")', function() {
      // uncomment below and update the code to test the property owners
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property thirdPartyReferences (base name: "thirdPartyReferences")', function() {
      // uncomment below and update the code to test the property thirdPartyReferences
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

    it('should have the property documents (base name: "documents")', function() {
      // uncomment below and update the code to test the property documents
      //var instane = new YlThirdPartyLoanApiClient.LoanModel();
      //expect(instance).to.be();
    });

  });

}));
