/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YlThirdPartyLoanApiClient);
  }
}(this, function(expect, YlThirdPartyLoanApiClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RefinancingLoanDetailsModel', function() {
    it('should create an instance of RefinancingLoanDetailsModel', function() {
      // uncomment below and update the code to test RefinancingLoanDetailsModel
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be.a(YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel);
    });

    it('should have the property loanId (base name: "loanId")', function() {
      // uncomment below and update the code to test the property loanId
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property loanNumber (base name: "loanNumber")', function() {
      // uncomment below and update the code to test the property loanNumber
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanOriginalAmount (base name: "oldLoanOriginalAmount")', function() {
      // uncomment below and update the code to test the property oldLoanOriginalAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanFundedAmount (base name: "oldLoanFundedAmount")', function() {
      // uncomment below and update the code to test the property oldLoanFundedAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanDiscount (base name: "oldLoanDiscount")', function() {
      // uncomment below and update the code to test the property oldLoanDiscount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanDiscountAmount (base name: "oldLoanDiscountAmount")', function() {
      // uncomment below and update the code to test the property oldLoanDiscountAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanRepaymentAmount (base name: "oldLoanRepaymentAmount")', function() {
      // uncomment below and update the code to test the property oldLoanRepaymentAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanRepaymentFundedAmount (base name: "oldLoanRepaymentFundedAmount")', function() {
      // uncomment below and update the code to test the property oldLoanRepaymentFundedAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanRepaymentDiscountAmount (base name: "oldLoanRepaymentDiscountAmount")', function() {
      // uncomment below and update the code to test the property oldLoanRepaymentDiscountAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanUnpaidAmount (base name: "oldLoanUnpaidAmount")', function() {
      // uncomment below and update the code to test the property oldLoanUnpaidAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanUnpaidFundedAmount (base name: "oldLoanUnpaidFundedAmount")', function() {
      // uncomment below and update the code to test the property oldLoanUnpaidFundedAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property oldLoanUnpaidDiscountAmount (base name: "oldLoanUnpaidDiscountAmount")', function() {
      // uncomment below and update the code to test the property oldLoanUnpaidDiscountAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property newLoanIncreaseAmount (base name: "newLoanIncreaseAmount")', function() {
      // uncomment below and update the code to test the property newLoanIncreaseAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property newLoanIncreaseFundedAmount (base name: "newLoanIncreaseFundedAmount")', function() {
      // uncomment below and update the code to test the property newLoanIncreaseFundedAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property newLoanIncreaseDiscount (base name: "newLoanIncreaseDiscount")', function() {
      // uncomment below and update the code to test the property newLoanIncreaseDiscount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property newLoanIncreaseDiscountAmount (base name: "newLoanIncreaseDiscountAmount")', function() {
      // uncomment below and update the code to test the property newLoanIncreaseDiscountAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property consolidatedLoanOriginalAmount (base name: "consolidatedLoanOriginalAmount")', function() {
      // uncomment below and update the code to test the property consolidatedLoanOriginalAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property consolidatedLoanFundedAmount (base name: "consolidatedLoanFundedAmount")', function() {
      // uncomment below and update the code to test the property consolidatedLoanFundedAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property consolidatedLoanDiscount (base name: "consolidatedLoanDiscount")', function() {
      // uncomment below and update the code to test the property consolidatedLoanDiscount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

    it('should have the property consolidatedLoanDiscountAmount (base name: "consolidatedLoanDiscountAmount")', function() {
      // uncomment below and update the code to test the property consolidatedLoanDiscountAmount
      //var instane = new YlThirdPartyLoanApiClient.RefinancingLoanDetailsModel();
      //expect(instance).to.be();
    });

  });

}));
