/**
 * Third Party Loan API
 * Through this API you can can retrieve loan data
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DefaultDetailsModel from './model/DefaultDetailsModel';
import DocumentMetadataModel from './model/DocumentMetadataModel';
import EarlyRenewalDetailsModel from './model/EarlyRenewalDetailsModel';
import LoanDocumentModel from './model/LoanDocumentModel';
import LoanFundingDetailsModel from './model/LoanFundingDetailsModel';
import LoanFundingPaymentModel from './model/LoanFundingPaymentModel';
import LoanModel from './model/LoanModel';
import LoanOwnerModel from './model/LoanOwnerModel';
import LoanRefinancingDetailsModel from './model/LoanRefinancingDetailsModel';
import LoanRepaymentModel from './model/LoanRepaymentModel';
import LoanWriteOffDetailsModel from './model/LoanWriteOffDetailsModel';
import LoansModel from './model/LoansModel';
import ProblemDetails from './model/ProblemDetails';
import RefinancingLoanDetailsModel from './model/RefinancingLoanDetailsModel';
import ThirdPartyReferenceModel from './model/ThirdPartyReferenceModel';
import LoansApi from './api/LoansApi';


/**
* Through_this_API_you_can_can_retrieve_loan_data.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var YlThirdPartyLoanApiClient = require('index'); // See note below*.
* var xxxSvc = new YlThirdPartyLoanApiClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new YlThirdPartyLoanApiClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new YlThirdPartyLoanApiClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new YlThirdPartyLoanApiClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DefaultDetailsModel model constructor.
     * @property {module:model/DefaultDetailsModel}
     */
    DefaultDetailsModel,

    /**
     * The DocumentMetadataModel model constructor.
     * @property {module:model/DocumentMetadataModel}
     */
    DocumentMetadataModel,

    /**
     * The EarlyRenewalDetailsModel model constructor.
     * @property {module:model/EarlyRenewalDetailsModel}
     */
    EarlyRenewalDetailsModel,

    /**
     * The LoanDocumentModel model constructor.
     * @property {module:model/LoanDocumentModel}
     */
    LoanDocumentModel,

    /**
     * The LoanFundingDetailsModel model constructor.
     * @property {module:model/LoanFundingDetailsModel}
     */
    LoanFundingDetailsModel,

    /**
     * The LoanFundingPaymentModel model constructor.
     * @property {module:model/LoanFundingPaymentModel}
     */
    LoanFundingPaymentModel,

    /**
     * The LoanModel model constructor.
     * @property {module:model/LoanModel}
     */
    LoanModel,

    /**
     * The LoanOwnerModel model constructor.
     * @property {module:model/LoanOwnerModel}
     */
    LoanOwnerModel,

    /**
     * The LoanRefinancingDetailsModel model constructor.
     * @property {module:model/LoanRefinancingDetailsModel}
     */
    LoanRefinancingDetailsModel,

    /**
     * The LoanRepaymentModel model constructor.
     * @property {module:model/LoanRepaymentModel}
     */
    LoanRepaymentModel,

    /**
     * The LoanWriteOffDetailsModel model constructor.
     * @property {module:model/LoanWriteOffDetailsModel}
     */
    LoanWriteOffDetailsModel,

    /**
     * The LoansModel model constructor.
     * @property {module:model/LoansModel}
     */
    LoansModel,

    /**
     * The ProblemDetails model constructor.
     * @property {module:model/ProblemDetails}
     */
    ProblemDetails,

    /**
     * The RefinancingLoanDetailsModel model constructor.
     * @property {module:model/RefinancingLoanDetailsModel}
     */
    RefinancingLoanDetailsModel,

    /**
     * The ThirdPartyReferenceModel model constructor.
     * @property {module:model/ThirdPartyReferenceModel}
     */
    ThirdPartyReferenceModel,

    /**
    * The LoansApi service constructor.
    * @property {module:api/LoansApi}
    */
    LoansApi
};
